// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chyfqmdveyloyvweoani.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoeWZxbWR2ZXlsb3l2d2VvYW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODk5OTAsImV4cCI6MjA2NTA2NTk5MH0.xiBb4SrLWGam3sMbBmXWtzYblOab57hV8xr8mZx4KQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);